#!/bin/bash

get_record_info() {
  domain=$1
  subdomain=$2

  if [ -z "$subdomain" ]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
  else
    subdomains=("$subdomain")
  fi

  for sub in "${subdomains[@]}"; do
    record_type=$(dig "$sub.$domain" | awk '/ANSWER SECTION:/ {getline; print $4}')
    destination=$(dig "$sub.$domain" | awk '/ANSWER SECTION:/ {getline; getline; print $5}')

    echo "The subdomain $sub is a $record_type record and points to $destination"
  done
}

get_record_info "$1" "$2"
